name: Code Quality Check

on:
  pull_request:
    branches: [main, dev]

jobs:
  lint-format:
    name: ESLint & Prettier Check
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.pull_request.title, 'patchnote/')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting with Prettier
        run: npm run format:check

      - name: Lint with ESLint
        run: npm run lint
